import { AurelProfile, DSPParameters, MicCorrectionModel } from './types';

export const BASE_DSP_PARAMS: DSPParameters = {
  preGainDb: 18,
  noiseGate: {
    enabled: true,
    thresholdDb: -46,
    reductionDb: -24,
    attackMs: 10,
    releaseMs: 180,
  },
  eq: {
    enabled: true,
    hpfFreq: 80,
    warmthFreq: 155,
    warmthGainDb: 4.5,
    mudFreq: 360,
    mudGainDb: -4.0,
    mudQ: 1.6,
    presenceFreq: 4200,
    presenceGainDb: 5.0,
    presenceQ: 1.3,
    airFreq: 11000,
    airGainDb: 2.5,
  },
  compressor: {
    enabled: true,
    thresholdDb: -22,
    ratio: 4.5,
    attackMs: 12,
    releaseMs: 160,
    kneeDb: 14,
  },
  deEsser: {
    enabled: true,
    freq: 6500,
    reductionDb: -3.5,
  },
  limiter: {
    enabled: true,
    ceilingDb: -1.0,
  },
  outputGainDb: 0,
};

export const NOISE_MAP: Record<string, { label: string; desc: string; floor: string; thresholdDb: number; reductionDb: number }> = {
  off: {
    label: 'Off',
    desc: 'Your room is passed through untouched.',
    floor: '−48 dB',
    thresholdDb: -90,
    reductionDb: 0,
  },
  light: {
    label: 'Light',
    desc: 'Takes the edge off steady hum and hiss. Most natural.',
    floor: '−62 dB',
    thresholdDb: -56,
    reductionDb: -14,
  },
  balanced: {
    label: 'Balanced',
    desc: 'Removes fans, keyboard clicks and room echo while keeping breaths natural.',
    floor: '−74 dB',
    thresholdDb: -46,
    reductionDb: -24,
  },
  strong: {
    label: 'Strong',
    desc: 'For loud rooms. Silences everything that is not your voice.',
    floor: '−86 dB',
    thresholdDb: -38,
    reductionDb: -36,
  },
};

export const AUREL_PROFILES: AurelProfile[] = [
  {
    id: 'broadcast',
    name: 'Broadcast',
    desc: 'Deep, close and controlled. The late-night radio voice.',
    tags: 'Warm lows · Tight dynamics',
    curve: 'M0 30 C18 30 28 11 58 12 S108 25 140 25 S198 17 228 19 S254 27 260 29',
    isBuiltIn: true,
    params: {
      ...BASE_DSP_PARAMS,
      preGainDb: 20,
      eq: {
        enabled: true,
        hpfFreq: 75,
        warmthFreq: 150,
        warmthGainDb: 5.5,
        mudFreq: 340,
        mudGainDb: -4.0,
        mudQ: 1.6,
        presenceFreq: 4200,
        presenceGainDb: 4.5,
        presenceQ: 1.3,
        airFreq: 11000,
        airGainDb: 3.0,
      },
      compressor: {
        enabled: true,
        thresholdDb: -22,
        ratio: 4.8,
        attackMs: 10,
        releaseMs: 160,
        kneeDb: 14,
      },
    },
  },
  {
    id: 'podcast',
    name: 'Podcast',
    desc: 'Rich and even for long-form talk, interviews and narration.',
    tags: 'Full body · Smooth',
    curve: 'M0 33 C25 33 40 17 72 17 S120 23 150 22 S210 16 240 18 S258 25 260 27',
    isBuiltIn: true,
    params: {
      ...BASE_DSP_PARAMS,
      preGainDb: 18,
      eq: {
        enabled: true,
        hpfFreq: 80,
        warmthFreq: 160,
        warmthGainDb: 4.0,
        mudFreq: 360,
        mudGainDb: -3.5,
        mudQ: 1.5,
        presenceFreq: 3800,
        presenceGainDb: 5.0,
        presenceQ: 1.2,
        airFreq: 10500,
        airGainDb: 2.5,
      },
      compressor: {
        enabled: true,
        thresholdDb: -24,
        ratio: 4.0,
        attackMs: 12,
        releaseMs: 180,
        kneeDb: 16,
      },
    },
  },
  {
    id: 'clear',
    name: 'Clear Speech',
    desc: 'Crisp and intelligible. Tuned for meetings and calls.',
    tags: 'Low cut · Presence',
    curve: 'M0 39 C20 39 34 27 60 25 S120 23 150 21 S190 9 215 11 S250 21 260 25',
    isBuiltIn: true,
    params: {
      ...BASE_DSP_PARAMS,
      preGainDb: 17,
      eq: {
        enabled: true,
        hpfFreq: 95,
        warmthFreq: 170,
        warmthGainDb: 2.0,
        mudFreq: 390,
        mudGainDb: -4.5,
        mudQ: 1.6,
        presenceFreq: 4400,
        presenceGainDb: 6.5,
        presenceQ: 1.4,
        airFreq: 12000,
        airGainDb: 3.0,
      },
      compressor: {
        enabled: true,
        thresholdDb: -22,
        ratio: 3.5,
        attackMs: 8,
        releaseMs: 140,
        kneeDb: 12,
      },
    },
  },
  {
    id: 'condenser',
    name: 'Studio Condenser',
    desc: 'Open, airy detail with a polished top end.',
    tags: 'Air · Detail',
    curve: 'M0 34 C30 34 50 24 90 24 S150 25 180 21 S230 8 260 7',
    isBuiltIn: true,
    params: {
      ...BASE_DSP_PARAMS,
      preGainDb: 16,
      eq: {
        enabled: true,
        hpfFreq: 70,
        warmthFreq: 150,
        warmthGainDb: 2.5,
        mudFreq: 320,
        mudGainDb: -3.0,
        mudQ: 1.5,
        presenceFreq: 4600,
        presenceGainDb: 5.0,
        presenceQ: 1.2,
        airFreq: 12500,
        airGainDb: 5.5,
      },
      compressor: {
        enabled: true,
        thresholdDb: -23,
        ratio: 3.8,
        attackMs: 14,
        releaseMs: 170,
        kneeDb: 14,
      },
    },
  },
  {
    id: 'natural',
    name: 'Natural',
    desc: 'Light cleanup only. Still you, just clearer and louder.',
    tags: 'Transparent',
    curve: 'M0 29 C30 26 60 24 130 24 S230 24 260 25',
    isBuiltIn: true,
    params: {
      ...BASE_DSP_PARAMS,
      preGainDb: 15,
      eq: {
        enabled: true,
        hpfFreq: 70,
        warmthFreq: 160,
        warmthGainDb: 1.0,
        mudFreq: 350,
        mudGainDb: -1.5,
        mudQ: 1.2,
        presenceFreq: 4000,
        presenceGainDb: 2.0,
        presenceQ: 1.0,
        airFreq: 11000,
        airGainDb: 1.5,
      },
      compressor: {
        enabled: true,
        thresholdDb: -26,
        ratio: 2.5,
        attackMs: 15,
        releaseMs: 200,
        kneeDb: 18,
      },
    },
  },
];

export const MIC_CORRECTION_MODELS: MicCorrectionModel[] = [
  {
    id: 'none',
    name: 'Raw / Generic Microphone',
    category: 'Neutral',
    description: 'Flat baseline response with no specific acoustic curve inversion.',
    eqOffsets: {},
  },
  {
    id: 'maono-pd100',
    name: 'Maono PD100 Dynamic',
    category: 'Budget Dynamic',
    description: 'Removes 380 Hz capsule boxiness and compensates high-frequency roll-off with radio presence.',
    eqOffsets: { mudGain: -3.5, airGain: 3.0, warmthGain: 2.0 },
  },
  {
    id: 'shure-sm7b',
    name: 'Shure SM7B Emulation',
    category: 'Broadcast Standard',
    description: 'Emulates the signature deep chest low-end and silky mid presence of the radio legend.',
    eqOffsets: { warmthGain: 4.5, mudGain: -2.0, presenceGain: 3.5 },
  },
  {
    id: 'blue-yeti',
    name: 'Blue Yeti USB Condenser',
    category: 'USB Condenser',
    description: 'Tames harsh 6.2 kHz capsule glare, cuts desk rumble, and softens room reflections.',
    eqOffsets: { hpfFreq: 95, mudGain: -2.5, presenceGain: -1.5, airGain: 1.0 },
  },
  {
    id: 'elgato-wave',
    name: 'Elgato Wave:3',
    category: 'Streaming Condenser',
    description: 'Balances upper midrange brightness and tightens lower vocal body.',
    eqOffsets: { warmthGain: 2.5, presenceGain: -2.0, airGain: 1.5 },
  },
  {
    id: 'rode-procaster',
    name: 'Røde Procaster / PodMic',
    category: 'Broadcast Dynamic',
    description: 'Smooths the aggressive 4.5 kHz peak while elevating deep warmth.',
    eqOffsets: { warmthGain: 3.0, mudGain: -2.0, airGain: 2.5 },
  },
  {
    id: 'laptop-mic',
    name: 'Built-in Laptop / Realtek Mic',
    category: 'Integrated',
    description: 'Aggressive acoustic de-hollowness, room resonance suppression, and vocal intelligibility boost.',
    eqOffsets: { hpfFreq: 110, mudGain: -5.0, presenceGain: 5.5, airGain: 3.0 },
  },
];
